# Generated by Django 5.0.7 on 2024-07-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyCalls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="신고 날짜")),
                ("category", models.CharField(max_length=255, verbose_name="사건 분류")),
                ("location", models.CharField(max_length=255, verbose_name="사건 발생 장소")),
                ("details", models.TextField(verbose_name="구체적인 현장 상태")),
                (
                    "estimated_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="추정 주소"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
