# Generated by Django 4.2.13 on 2024-07-15 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stt", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat_log",
        ),
    ]
